name: terraform docs

on:
  push:
    branches: [main]
    paths:
      - "**.tf"
  pull_request:
    branches: [main]
    paths:
      - "**.tf"

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: terraform docs
        uses: terraform-docs/gh-actions@v0.9.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
