name: terraform example

on:
  workflow_dispatch:

jobs:
  terraform:
    # run this on self-hosted runner
    runs-on: [self-hosted, azure, '${{ matrix.os }}']
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, Windows]
    env:
      ARM_USE_MSI: true
      TF_INPUT: false
      TF_IN_AUTOMATION: true
      # example: how to pass git access token to terraform as variable
      TF_VAR_git_token: ${{ secrets.github_token }}
      TF_VAR_product_name: "testrunner"

    defaults:
      run:
        working-directory: './examples/basic'

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
          #  setting to true seems cause issues with this task on azure runner
          terraform_wrapper: false

      - name: login to Azure
        run: |
          az login --identity

          # uncomment if using user-defined managed identity for runner
          echo "ARM_SUBSCRIPTION_ID=$(az account show --output tsv --query id)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --output tsv --query tenantId)" >> $GITHUB_ENV

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
