name: terraform docs

on:
  push:
    branches: [main]
    paths:
      - "**.tf"
  pull_request:
    branches: [main]
    paths:
      - "**.tf"

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the ReadME.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v0.9.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
