name: test wsl on windows

on:

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: code

env:
  environment: dev

jobs:
  wsl:
    runs-on: [ self-hosted, azure, windows ]
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          update: 'true'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install packages
        run: dotnet restore ./webapi
      - name: Publish
        run: dotnet publish ./webapi -c Release -o ./publish/
      - name: "Upload Api"
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: code/publish/**